// Concept tags and wrong-answer diagnoses for content/chemistry.js.
// Key "unit.question" -> [concept index, { wrongChoiceIndex: "why a student might pick it" }]
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["chemistry"] = {
  "0.0": [0, { 0: "0.5 divides the molar mass by the mass. Moles = mass ÷ molar mass = 36 ÷ 18.", 2: "18 g/mol is the molar mass, not the number of moles.", 3: "648 multiplies instead of dividing." }],
  "0.1": [3, { 0: "Li has only one valence electron, far from the nucleus, so it's easy to remove.", 1: "Na is lower in the group and to the left, so its IE is even lower than Li's.", 2: "O has a high IE, but F is farther right, with a higher effective nuclear charge." }],
  "0.2": [3, { 0: "Across a period the number of shells stays the SAME. Adding shells happens down a group.", 2: "Neutrons are neutral, so they don't repel electrons.", 3: "Shielding stays roughly constant across a period. The rising proton count dominates." }],
  "0.3": [0, { 0: "That ignores the 25% of Cl-37. Weight each isotope by its abundance.", 2: "36.0 averages 35 and 37 equally, but Cl-35 is three times more common.", 3: "37.0 is just the heavier isotope." }],
  "1.0": [2, { 0: "Trigonal planar has NO lone pairs on the central atom. N has one.", 1: "Tetrahedral is the ELECTRON geometry. The shape ignores the lone pair.", 3: "Bent needs two lone pairs, like water." }],
  "1.1": [3, { 0: "Carbon is fairly electronegative, and the C=O bonds ARE polar.", 2: "Carbon in CO₂ has no lone pairs. Its two double bonds make it linear.", 3: "CO₂ is covalent (molecular), not ionic." }],
  "1.2": [2, { 0: "sp means 2 electron groups (linear). CH₄ has 4.", 1: "sp² means 3 groups (trigonal planar). Count carbon's four bonds.", 3: "sp³d means 5 groups, which is too many for carbon." }],
  "1.3": [0, { 0: "Substitutional alloys swap in similar-sized atoms. Small carbon atoms fit in the GAPS.", 2: "Steel is metallic, not ionic.", 3: "Network covalent solids (like diamond) aren't metal alloys." }],
  "2.0": [0, { 0: "More electrons does strengthen dispersion forces, but H₂O's hydrogen bonds are much stronger.", 2: "Different intermolecular forces give different boiling points.", 3: "Size alone isn't enough here. Hydrogen bonding dominates." }],
  "2.1": [2, { 0: "High T and low P is the MOST ideal: particles are fast and far apart.", 2: "High T keeps attractions minor, so it's not the worst case.", 3: "Low pressure keeps particles far apart, which is closer to ideal." }],
  "2.2": [3, { 0: "0.125 multiplies by 0.25 L instead of dividing.", 1: "0.50 is the moles. Divide by the volume in LITERS (0.250 L).", 3: "125 uses milliliters instead of liters." }],
  "2.3": [2, { 0: "At constant V and n, P ∝ T. Heating RAISES pressure.", 2: "PV = nRT: if T doubles with V and n constant, P must change.", 3: "The relationship is linear, not squared." }],
  "3.0": [2, { 0: "The mole ratio of H₂ to H₂O is 2:2 = 1:1, so it doesn't halve.", 2: "O₂ is in excess, so H₂ alone determines the product: 4 mol.", 3: "8 mol doubles instead of using the 1:1 ratio." }],
  "3.1": [1, { 0: "Na⁺ and NO₃⁻ are SPECTATORS. They stay dissolved.", 2: "That's the molecular equation. Net ionic removes the spectators.", 3: "The reactants are ions (Ag⁺, Cl⁻), not neutral atoms." }],
  "3.2": [3, { 0: "Check the sum: 2(+1) + S + 4(−2) = 0 gives S = +6.", 1: "+4 is sulfur's oxidation number in SO₂, not H₂SO₄.", 3: "−2 is oxygen's oxidation number. Solve for S." }],
  "3.3": [2, { 0: "1 mol is the N₂ that gets USED. The product ratio is 1 N₂ : 2 NH₃.", 2: "3 mol H₂ can't make 3 mol NH₃. The ratio is 3 H₂ : 2 NH₃.", 3: "4 mol assumes N₂ is limiting. H₂ runs out first." }],
  "4.0": [0, { 0: "Zero order means the rate doesn't change with [A].", 1: "First order would DOUBLE the rate. Quadrupling means 2² = 4.", 3: "Third order would give 2³ = 8 times the rate." }],
  "4.1": [1, { 0: "[A] vs t is linear for ZERO order.", 2: "1/[A] vs t is linear for SECOND order.", 3: "No standard order gives a linear [A]² plot." }],
  "4.2": [2, { 0: "A catalyst doesn't change ΔH. Reactants and products stay the same.", 2: "A catalyst doesn't heat anything. It opens a lower-energy pathway.", 3: "A catalyst speeds both directions equally, so equilibrium doesn't shift." }],
  "4.3": [1, { 0: "Each half-life halves what's left: (1/2)³ after three half-lives.", 1: "1/4 is two half-lives (20 min). 30 min is three.", 3: "1/16 is four half-lives." }],
  "5.0": [1, { 0: "418 J forgets the mass of 100 g (or uses 10 g).", 2: "20.9 drops two factors of 10. Use q = mcΔT = 100 × 4.18 × 5.0.", 3: "4180 J uses ΔT = 10 instead of 5." }],
  "5.1": [1, { 0: "Energy is released when bonds FORM. Breaking bonds always costs energy.", 2: "Bonds hold energy, so breaking them takes energy.", 3: "Breaking a bond is endothermic, not exothermic." }],
  "5.2": [2, { 0: "Reversing FLIPS the sign, so the answer is positive.", 1: "Don't forget to double: coefficients ×2 means ΔH ×2.", 3: "Reversing flips the sign, and doubling multiplies (not halves)." }],
  "5.3": [0, { 0: "The WATER gained heat, so the reaction RELEASED it.", 2: "A temperature change means heat was transferred.", 3: "The warming water tells us the direction of heat flow." }],
  "6.0": [2, { 0: "A HUGE K means products dominate.", 2: "K = 1 would mean comparable amounts. 10⁸ is far larger.", 3: "The size of K tells you directly." }],
  "6.1": [2, { 0: "Q < K means the product ratio is too LOW, so more products form.", 2: "Q ≠ K means the system isn't at equilibrium yet.", 3: "Reactions don't stop. They shift until Q = K." }],
  "6.2": [2, { 0: "The left has 4 mol of gas and the right has 2. Squeezing favors FEWER moles, which is the right.", 2: "The two sides have different numbers of gas moles, so volume matters.", 3: "Only temperature changes K. Volume shifts the position." }],
  "6.3": [3, { 0: "Pure solids are left out of K expressions.", 2: "The solid isn't included at all.", 3: "Equilibrium expressions MULTIPLY concentrations. They don't add them." }],
  "7.0": [0, { 0: "0.010 = 10⁻², so pH = 2.", 2: "12 is the pOH. HCl is an acid, so pH < 7.", 3: "0.01 is [H⁺]. pH is −log of that." }],
  "7.1": [3, { 0: "pH 7 happens at equivalence for a STRONG acid. For a weak acid at HALF-equivalence, pH = pKa.", 2: "pH 14 would mean very strong base, which is way past equivalence.", 3: "At half-equivalence, [HA] = [A⁻]. Half the acid remains." }],
  "7.2": [1, { 0: "HCl is a STRONG acid. Buffers need a WEAK acid and its conjugate base.", 2: "There's no conjugate pair here.", 3: "HNO₃ is a strong acid, so it can't buffer." }],
  "7.3": [2, { 0: "The pH scale is logarithmic. Each unit is ×10, not ×1.", 1: "Two units means 10 × 10 = 100, not 20.", 3: "Three factors of 10 would be 3 pH units." }],
  "8.0": [1, { 1: "Both terms make ΔG negative, so temperature doesn't matter.", 2: "ΔS > 0 means −TΔS < 0 at any T, so it's not only at low T.", 3: "ΔG = (−) − T(+) is always negative, so it's always favored." }],
  "8.1": [1, { 1: "A gas is produced from a solid, so disorder increases.", 2: "Making a gas changes entropy significantly.", 3: "Gas formation is a clear sign of ΔS > 0." }],
  "8.2": [2, { 0: "The cathode is for REDUCTION. Remember \"AN OX, RED CAT.\"", 2: "The salt bridge carries ions to balance charge. No reaction happens there.", 3: "The wire carries electrons, but the reaction happens at the electrodes." }],
  "8.3": [2, { 0: "Positive E° gives NEGATIVE ΔG° (ΔG° = −nFE°).", 2: "E° > 0 means ΔG° isn't zero.", 3: "ΔG° < 0 means K > 1, not K < 1." }],
};
