// Concept tags and wrong-answer diagnoses for content/physics-2.js.
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["physics-2"] = {
  "0.0": [1, { 0: "Constant temperature means ΔU = 0 for an ideal gas, so internal energy can't rise.", 2: "Work is done ON the gas, so heat must LEAVE to keep ΔU = 0.", 3: "In compression, work is done ON the gas, not by it, and ΔU stays 0." }],
  "0.1": [0, { 0: "Average KE is directly proportional to Kelvin temperature, so it can't halve.", 1: "Temperature IS a measure of average kinetic energy.", 3: "The relationship is linear, not squared." }],
  "0.2": [2, { 0: "The slope isn't work. Work = ∫P dV, the AREA under the curve.", 2: "Pressure alone isn't energy. You need P × ΔV.", 3: "ΔV alone has units of volume, not energy." }],
  "0.3": [1, { 1: "Heat IS added. It's the work that's zero at constant volume.", 2: "The gas absorbs heat and does no work, so U rises.", 3: "No volume change means no work is done." }],
  "1.0": [0, { 0: "That's only one doubling. Both charges double (×4) AND the distance halves (×4).", 1: "That misses a factor: q's give ×4, and 1/r² gives another ×4.", 2: "Halving r multiplies F by 4 (inverse square), not 2." }],
  "1.1": [1, { 0: "That's how a PROTON would move. Electrons are pushed opposite to E.", 2: "The force is along the field line, not perpendicular to it.", 3: "Any charge in a field feels a force." }],
  "1.2": [2, { 0: "Along an equipotential ΔV = 0, so W = qΔV = 0.", 1: "Zero ΔV means zero work, with no sign to worry about.", 3: "W = qΔV, and ΔV = 0 makes it zero for any charge." }],
  "1.3": [3, { 0: "In a conductor, charges repel to the SURFACE.", 2: "Like charges push away from each other and from the center.", 3: "An isolated conductor holds its charge on the surface." }],
  "2.0": [1, { 0: "12 Ω is the SERIES sum. Parallel resistance is smaller than either resistor.", 1: "6 Ω would mean nothing changed. Adding a path lowers resistance.", 3: "1/3 is 1/R. Flip it to get R = 3 Ω." }],
  "2.1": [0, { 0: "R ∝ L, so a longer wire has MORE resistance.", 1: "Length directly affects resistance: R = ρL/A.", 3: "It's linear in L. Quadrupling would need length × 4 or area ÷ 4." }],
  "2.2": [1, { 0: "Parallel branches LOWER total resistance, so current increases.", 1: "The new branch draws its own current, so the total increases.", 3: "The battery still drives current through both bulbs." }],
  "2.3": [3, { 0: "Maximum current happens at the START, when the capacitor is empty.", 2: "At steady state no current flows through the capacitor branch.", 3: "The current decreases toward zero as the capacitor charges." }],
  "3.0": [0, { 0: "sin 0° = 0, so the force is zero, not maximum.", 2: "Magnetic forces are always perpendicular to B and v.", 3: "The force is perpendicular to v, never opposite to it." }],
  "3.1": [0, { 0: "The force is perpendicular to the motion, so it does no work.", 1: "A perpendicular force doesn't slow the particle.", 3: "qvB is a force, not work. The work is zero." }],
  "3.2": [1, { 1: "OPPOSITE currents repel. Same-direction currents attract.", 2: "Each wire sits in the other's magnetic field, so they feel forces.", 3: "The forces are along the line between the wires, so they don't rotate them." }],
  "3.3": [3, { 0: "A steady field gives no CHANGE in flux, so there's no emf.", 2: "Alternating current needs a changing flux, like a moving or rotating magnet.", 3: "Nothing is changing, so there's nothing to increase." }],
  "4.0": [1, { 0: "Entering a slower medium (higher n), light bends TOWARD the normal and slows down.", 2: "At an angle, the speed change bends the ray.", 3: "Total reflection only happens going from high n to low n." }],
  "4.1": [2, { 0: "Air → water goes INTO a higher n, so no TIR is possible.", 2: "Air → glass also goes to a higher n.", 3: "Along the normal, light passes straight through." }],
  "4.2": [3, { 0: "Virtual, upright images need the object INSIDE f.", 2: "Real images from a single lens are inverted, not upright.", 3: "At 2f the lens forms a real image at 2f." }],
  "4.3": [3, { 0: "Diverging lenses can't form real images of real objects.", 2: "Diverging lenses always make SMALLER images.", 3: "Virtual images from lenses are upright, not inverted." }],
  "5.0": [0, { 0: "v is fixed by the medium, so doubling f HALVES λ.", 2: "v = fλ, so if f changes, λ must change.", 3: "It's inversely proportional, not squared." }],
  "5.1": [1, { 0: "An approaching source RAISES the observed frequency.", 2: "Relative motion changes the observed pitch (the Doppler effect).", 3: "Motion doesn't silence sound." }],
  "5.2": [3, { 0: "A larger λ means LARGER angles (d sin θ = mλ), so fringes spread out.", 2: "Changing λ shifts the fringes. They don't disappear.", 3: "Fringe spacing depends on λ." }],
  "5.3": [3, { 0: "L/2 is the SECOND harmonic's half-wavelength. The fundamental fits half a wavelength in L.", 1: "λ = L is the second harmonic. The fundamental has λ = 2L.", 3: "4L applies to a pipe closed at one end, not a string fixed at both ends." }],
  "6.0": [0, { 0: "More intense light below threshold still has photons that are too weak.", 1: "Electron energy depends on FREQUENCY, not intensity.", 3: "The work function is a property of the metal." }],
  "6.1": [1, { 0: "3.4 eV is only one level's magnitude. Use the difference.", 2: "13.6 eV would be ionizing from the ground state.", 3: "17.0 adds the levels. Subtract instead." }],
  "6.2": [3, { 0: "Half-lives HALVE the sample, so it doesn't divide by 3.", 1: "That's 1/2 × 1/3. It should be (1/2)³.", 3: "1/9 uses thirds. Each half-life halves the sample." }],
  "6.3": [3, { 1: "That swaps the numbers: the mass number drops by 4 and the atomic number by 2.", 2: "That describes beta-minus decay (a neutron → a proton).", 3: "Alpha particles carry away 4 nucleons, so the mass number drops by 4." }],
};
