// Concept tags and wrong-answer diagnoses for content/physics-1.js.
// Key "unit.question" -> [concept index, { wrongChoiceIndex: "why a student might pick it" }]
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["physics-1"] = {
  "0.0": [2, { 0: "5 m/s would be g × ½ s. Use v = v₀ + gt with t = 2 s.", 1: "10 m/s is the speed after 1 second, not 2.", 3: "40 m/s doubles the correct answer. Recheck v = 0 + 10 × 2." }],
  "0.1": [1, { 0: "Acceleration is the SLOPE of a v–t graph. The area is displacement.", 2: "A velocity graph has no force information without the mass.", 3: "The speed at the end is read off the graph's final point, not found from the area." }],
  "0.2": [3, { 0: "Gravity never switches off, so acceleration is always g downward. Only the vertical velocity hits zero.", 2: "Horizontal velocity stays constant throughout the flight (no horizontal force).", 3: "At the top, velocity is horizontal, but acceleration is still g downward." }],
  "0.3": [3, { 0: "Both start with zero VERTICAL velocity, and horizontal motion doesn't affect fall time.", 1: "Throwing B sideways adds horizontal speed but doesn't change its vertical motion.", 3: "Horizontal speed changes WHERE B lands, not WHEN." }],
  "1.0": [0, { 1: "This is the \"force of motion\" misconception. Moving at constant velocity needs NO net force.", 2: "A net force opposite the motion would slow the object down, but its velocity is constant.", 3: "Weight is just one force. The NET force is what's zero." }],
  "1.1": [0, { 0: "The car accelerates more, but Newton's 3rd law makes the forces equal.", 1: "The truck's bigger mass doesn't mean it pushes harder. The forces are an equal-and-opposite pair.", 3: "Both vehicles clearly feel a force." }],
  "1.2": [0, { 0: "2 m/s² subtracts twice, or divides 4 by 2. F_net = 10 − 4 = 6 N.", 2: "5 m/s² ignores friction: 10/2. Friction reduces the net force.", 3: "7 m/s² ADDS friction. Friction opposes the push." }],
  "1.3": [3, { 0: "Gravity weakens with distance. It doesn't strengthen.", 1: "It's inverse-SQUARE: 1/2² = 1/4, not 1/2.", 3: "Moving farther apart DEcreases the force." }],
  "1.4": [0, { 1: "\"Less than your weight\" happens when accelerating DOWNWARD.", 2: "Your weight only matches the reading at constant velocity. Upward acceleration needs extra normal force.", 3: "A reading of zero is free fall. You're accelerating up, not falling." }],
  "2.0": [2, { 0: "5 m/s uses v = h. Use energy conservation: v = √(2gh).", 1: "7 m/s is √50, which forgets the factor of 2 in √(2gh).", 3: "50 is 2gh = v². Take the square root." }],
  "2.1": [0, { 0: "The normal force is perpendicular to the motion, so W = Fd cos 90° = 0.", 1: "Friction does negative work here. The normal force is perpendicular, so it does zero.", 3: "The box doesn't change height, and the normal force isn't gravity." }],
  "2.2": [1, { 0: "KE = ½mv². Because v is squared, doubling v multiplies KE by 4.", 1: "Square the factor: 2² = 4.", 3: "Changing speed always changes kinetic energy." }],
  "2.3": [3, { 0: "Check the work: mgh = 50 × 10 × 2 = 1000 J, then divide by 4 s.", 1: "100 W forgets g (50 × 2 = 100). Use mgh.", 3: "1000 J is the WORK. Power divides it by the time, 4 s." }],
  "3.0": [0, { 0: "The change in momentum is fixed (you go from moving to stopped). The airbag spreads it over more time.", 2: "An airbag can't change your mass.", 3: "Energy can't vanish instantly. The airbag works by making the stop take LONGER." }],
  "3.1": [1, { 0: "Recheck: 2 × 3 = 6 kg·m/s, shared by 3 kg, gives 2 m/s.", 1: "1.5 m/s divides by the wrong total mass. It's 2 + 1 = 3 kg.", 3: "3 m/s ignores the added mass of the second cart." }],
  "3.2": [1, { 0: "Check: the ball's momentum is 2 × 6 = 12, and 12/60 = 0.2 m/s.", 2: "2 m/s swaps the masses. Use 60v = 2 × 6.", 3: "The skater is much heavier than the ball, so she recoils much slower." }],
  "3.3": [0, { 1: "4 N·s forgets the ½ in a triangle's area.", 2: "10 is the peak force, not the area under the graph.", 3: "25 divides instead of multiplying. Area = ½ × base × height." }],
  "4.0": [1, { 0: "Your push is the same. The longer lever arm increases the TORQUE.", 2: "Friction at the bolt doesn't change with wrench length.", 3: "The benefit comes from torque (τ = rF), not rotational inertia." }],
  "4.1": [3, { 0: "Balance torques: 30 × 2 = 40 × d, so d = 1.5 m.", 2: "Equal distances only balance equal masses.", 3: "2.7 m inverts the ratio. The heavier child must sit CLOSER to the pivot." }],
  "4.2": [2, { 1: "The disk has mass closer to the center, which gives a SMALLER I.", 2: "Same mass isn't enough. How far the mass is from the axis matters.", 3: "Rotational inertia depends on mass distribution, not speed." }],
  "4.3": [2, { 0: "α = τ/I. More torque gives MORE angular acceleration.", 1: "Torque directly causes angular acceleration, so α changes.", 3: "The relationship is linear, not squared." }],
  "5.0": [1, { 0: "L = Iω is conserved. A smaller I means a LARGER ω.", 2: "Pulling in her arms changes I, so ω must change to keep L constant.", 3: "There's no external torque to stop her." }],
  "5.1": [0, { 1: "The hoop puts MORE energy into spinning, leaving less for forward speed.", 2: "Shape matters: different I values split the energy differently.", 3: "Mass cancels out. The distribution (the shape) decides the race." }],
  "5.2": [1, { 0: "KE_rot = ½Iω². ω is squared, so it's 4×, not 2×.", 2: "Faster spinning means more energy, not less.", 3: "Changing ω changes rotational KE." }],
  "5.3": [2, { 0: "Farther away means SLOWER (angular momentum is conserved).", 2: "Speed depends on distance, not direction.", 3: "Orbital speed varies. It's faster closer in." }],
  "6.0": [0, { 0: "T ∝ √m. More mass means a longer period, not a shorter one.", 1: "Mass does affect a spring's period: T = 2π√(m/k).", 3: "It's the square root: √4 = 2, not 4." }],
  "6.1": [1, { 1: "T = 2π√(L/g). A smaller g gives a LARGER period.", 2: "A pendulum's period depends on g, which is lower on the Moon.", 3: "The pendulum still swings. Gravity is weaker, not absent." }],
  "6.2": [2, { 0: "At maximum stretch the mass momentarily stops, so v = 0.", 1: "At maximum compression v = 0, and all the energy is potential.", 3: "Speed changes constantly in SHM." }],
  "6.3": [1, { 0: "For small swings, the period doesn't depend on amplitude.", 1: "The period is independent of amplitude.", 3: "Amplitude doesn't enter T = 2π√(L/g)." }],
  "7.0": [0, { 0: "Check: ρgh = 1000 × 10 × 10 = 100,000 Pa.", 1: "10,000 Pa drops a factor of 10. Multiply all three: ρ, g and h.", 3: "One too many factors of 10. ρgh = 10⁵ Pa." }],
  "7.1": [1, { 0: "A net upward force would make the block rise, but it's at rest.", 2: "If buoyancy were less than the weight, the block would sink.", 3: "Any object in water feels a buoyant force." }],
  "7.2": [2, { 0: "Narrower pipe → FASTER flow (A₁v₁ = A₂v₂).", 1: "The same volume per second must pass through a smaller area, so it speeds up.", 3: "Speed scales with 1/A, not 1/A². Half the area doubles the speed." }],
  "7.3": [1, { 0: "Bernoulli: faster flow means LOWER pressure.", 2: "Different speeds mean different pressures.", 3: "There is still air pressure on top, just less than below." }],
};
