// Concept tags and wrong-answer diagnoses for content/psychology.js.
// Key "unit.question" -> [concept index, { wrongChoiceIndex: "why a student might pick it" }]
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["psychology"] = {
  "0.0": [0, { 0: "Antagonists BLOCK receptors. A drug that mimics a neurotransmitter and activates its receptor is an agonist.", 2: "A reuptake inhibitor keeps the body's own neurotransmitter in the synapse longer. This drug binds the receptor itself.", 3: "The drug acts at neural receptors like a neurotransmitter. It isn't a hormone traveling through the blood." }],
  "0.1": [2, { 0: "Wernicke's area handles COMPREHENSION. Sam understands speech but can't produce it, which points to Broca's.", 2: "The occipital lobe processes vision, not speech.", 3: "The cerebellum coordinates movement and balance, not language production." }],
  "0.2": [2, { 0: "The parasympathetic system CALMS the body (rest and digest). Racing heart and slowed digestion is arousal.", 2: "The somatic system controls voluntary muscles. Heart rate and digestion are autonomic.", 3: "The cerebellum coordinates movement. It doesn't trigger fight or flight." }],
  "0.3": [3, { 0: "Absolute threshold is the minimum stimulus detectable at all. This is about noticing a CHANGE in proportion to the original.", 2: "Sensory adaptation is declining sensitivity to a constant stimulus, not detecting differences.", 3: "Signal detection is about detecting stimuli amid noise and expectations, not a constant proportion." }],
  "0.4": [3, { 0: "NREM-1 is light, drifting sleep. Vivid dreams with muscle paralysis mark REM.", 1: "NREM-2 has sleep spindles, not vivid dreaming with paralysis.", 2: "NREM-3 is deep, slow-wave sleep. It's the hardest to wake from but isn't the vivid-dream stage." }],
  "1.0": [1, { 0: "Representativeness compares something to a prototype. Here, vivid news examples come to mind easily, which is availability.", 2: "Framing is about how information is worded, not how easily examples come to mind.", 3: "Mental set is sticking to a problem-solving approach that worked before." }],
  "1.1": [2, { 0: "Proactive = OLD blocks NEW. Here the NEW number blocks the OLD one, so it's retroactive.", 2: "She DID encode the old number. The problem is that new learning now interferes with retrieving it.", 3: "The primacy effect is about remembering the first items in a list." }],
  "1.2": [3, { 0: "Consistent scores mean the test IS reliable. Failing to predict performance is the validity problem.", 2: "A valid test would predict what it's supposed to predict, and this one doesn't.", 3: "The scores ARE consistent, so it's reliable." }],
  "1.3": [0, { 0: "Change blindness is missing a change in a scene. Here, attention elsewhere hides a clearly visible object.", 2: "Perceptual constancy is seeing objects as stable despite changing input.", 3: "Sensory adaptation is reduced response to a constant stimulus, not missing an unexpected one." }],
  "1.4": [2, { 0: "Recency is remembering the LAST items. The first items show the primacy effect.", 2: "The spacing effect is about spreading study sessions over time, not list position.", 3: "Next-in-line is forgetting what was said just before your turn to speak." }],
  "2.0": [3, { 0: "Positive reinforcement ADDS something pleasant. Here the beeping (unpleasant) is REMOVED.", 2: "Punishment decreases a behavior, but buckling up INCREASES.", 3: "Negative punishment removes something pleasant to decrease a behavior. The behavior increases here." }],
  "2.1": [3, { 0: "Fixed-ratio pays after a set number of responses. Slot machines are unpredictable.", 2: "Interval schedules depend on time passing. Slots depend on the number of plays.", 3: "Variable-interval is based on time, not the number of responses." }],
  "2.2": [0, { 0: "The sensorimotor stage is about object permanence (infants), not conservation.", 1: "Preoperational children FAIL conservation tasks. They think the taller glass holds more.", 3: "Formal operational means abstract reasoning. Conservation is already mastered earlier, in the concrete stage." }],
  "2.3": [2, { 0: "The UCS triggers a response naturally. The sound only works because it was paired with the drilling.", 1: "The UCR is the natural response (tensing at pain), not the sound.", 3: "The CR is the learned RESPONSE (tensing). The question asks about the stimulus." }],
  "3.0": [0, { 0: "Self-serving bias is about explaining YOUR OWN successes and failures, not a classmate's.", 2: "The just-world phenomenon is believing people get what they deserve. Here Jess ignores the situation.", 3: "Group polarization is about group discussions strengthening views." }],
  "3.1": [2, { 0: "Social facilitation is performing BETTER on easy tasks when watched. Here effort drops.", 2: "Deindividuation is losing self-restraint when anonymous, not slacking on shared work.", 3: "Groupthink is about seeking harmony in decisions, not individual effort." }],
  "3.2": [0, { 1: "Foot-in-the-door is agreeing to a big request after a small one. Here she changes her attitude to match her action.", 2: "Nobody is pressuring her to conform. The discomfort comes from her own inconsistency.", 3: "Mere exposure is liking things more through familiarity, not justifying a choice." }],
  "3.3": [3, { 0: "Openness is curiosity and imagination, not organization.", 2: "Agreeableness is kindness and cooperation.", 3: "Neuroticism is emotional instability, nearly the opposite of \"careful and dependable.\"" }],
  "3.4": [2, { 1: "Social facilitation is about performance when watched, not helping behavior.", 2: "No authority is giving orders here.", 3: "Self-serving bias is about explaining your own outcomes." }],
  "4.0": [0, { 0: "Alarm is the initial shock response. Weeks of stress that wear down the body is exhaustion.", 1: "In resistance the body is still coping. Getting sick and drained signals exhaustion.", 3: "Selye's model has no \"recovery\" stage: it's alarm, resistance, exhaustion." }],
  "4.1": [2, { 0: "\"Negative\" symptoms are things TAKEN AWAY (flat affect). Hallucinations ADD an experience, so they're positive.", 2: "Dissociative disorders involve disrupted identity or memory, not hallucinations.", 3: "Hallucinations are a hallmark of schizophrenia, not a symptom unique to bipolar disorder." }],
  "4.2": [3, { 0: "Aversive conditioning pairs a behavior with something unpleasant. This pairs relaxation with the feared object.", 2: "Psychoanalysis explores unconscious conflicts. It doesn't use gradual exposure.", 3: "Client-centered therapy focuses on empathy, not structured exposure." }],
  "4.3": [3, { 0: "Blocking dopamine is how antipsychotics work, not SSRIs.", 2: "The S in SSRI stands for serotonin, not GABA.", 3: "SSRIs target serotonin, not acetylcholine." }],
};
