// Concept tags and wrong-answer diagnoses for content/world-history.js.
window.AP_DIAG = window.AP_DIAG || {};
window.AP_DIAG["world-history"] = {
  "0.0": [0, { 0: "Buddhism spread through missionaries and trade, not through a new rice strain.", 2: "Civil-service exams continued. Champa rice affected FOOD and population.", 3: "The Mongol conquest came from the steppe. It wasn't caused by rice." }],
  "0.1": [0, { 0: "Song China deliberately moved AWAY from hereditary aristocracy toward merit-based exams.", 1: "The military mattered, but officials were chosen by exams.", 3: "Buddhist and Daoist clergy didn't staff the bureaucracy. Confucian scholars did." }],
  "0.2": [1, { 0: "They did the opposite: they translated and built on Greek works.", 2: "Movable type came from China, and the printing press from Gutenberg's Europe.", 3: "Dar al-Islam traded actively with Europe." }],
  "0.3": [3, { 0: "The Inca had no money-based taxes. They required LABOR.", 2: "Mit'a was a labor obligation, not a ritual.", 3: "The Inca and Aztecs weren't trading partners, and mit'a was internal labor." }],
  "1.0": [0, { 1: "No such bans explain it. Transport cost did.", 2: "Merchants of many classes traveled the routes.", 3: "It was about cost versus value, not legality." }],
  "1.1": [1, { 0: "Mongol rule made trade SAFER and expanded it.", 2: "The Mongols actually helped SPREAD the Black Death along trade routes.", 3: "Feudalism developed independently in Europe, centuries earlier." }],
  "1.2": [2, { 0: "Camels are for the SAHARA. The Indian Ocean ran on sailing.", 2: "Steamships came centuries later (the 1800s).", 3: "The Grand Canal was an internal Chinese waterway." }],
  "1.3": [3, { 0: "Islam reached Europe earlier (Spain, 700s). The pilgrimage showcased Mali's wealth.", 2: "Trans-Saharan trade continued and thrived.", 3: "The Atlantic slave trade began in the 1400s–1500s with Europeans." }],
  "2.0": [1, { 0: "The Ottomans used tax FARMING for revenue. The devshirme recruited people.", 2: "The devshirme served the state. It wasn't a mission to Europe.", 3: "The Taj Mahal is MUGHAL (in India), not Ottoman." }],
  "2.1": [3, { 1: "The Reformation was a split in Western Christianity, not an Islamic conflict.", 2: "Neither empire had Atlantic colonies.", 3: "The Opium Wars were 1800s Britain versus China." }],
  "2.2": [2, { 0: "The Taj Mahal is a building, a symbol of power, not a conquest.", 2: "Tax farming was about revenue, not legitimacy through art.", 3: "Joint-stock companies were European trading ventures." }],
  "2.3": [3, { 0: "The Reformation SPLIT Christianity rather than unifying it.", 2: "The Catholic Church survived and launched the Counter-Reformation.", 3: "The Reformation was a Christian split, unrelated to Islam." }],
  "3.0": [0, { 0: "The steam engine is 1700s industrial technology.", 2: "The telegraph is 1800s technology.", 3: "The cotton gin (1793) is industrial, not maritime." }],
  "3.1": [2, { 0: "Smallpox devastated the AMERICAS, not Afro-Eurasia.", 2: "The slave trade GREW with plantation economies.", 3: "Chinese trade expanded, absorbing American silver." }],
  "3.2": [1, { 0: "Joint-stock companies were owned by private SHAREHOLDERS, not run by monarchs.", 2: "These companies were deeply involved in slavery and exploitation.", 3: "They were tools of mercantilism, not an end to it." }],
  "3.3": [3, { 1: "The Pueblo Revolt happened in the Americas, against Spain.", 2: "The Ottomans weren't involved in North America.", 3: "It was 1680 and had nothing to do with industry." }],
  "4.0": [0, { 0: "The American Revolution was led by colonial elites, some of whom enslaved people.", 1: "The French Revolution overthrew a monarchy, but enslaved people didn't lead it.", 3: "The Glorious Revolution (1688) was an English change of monarchs." }],
  "4.1": [2, { 0: "Britain HAD colonies, and they supplied capital and markets.", 2: "Agriculture improved (the agricultural revolution). It wasn't banned.", 3: "China and India had larger populations. Resources and capital mattered more." }],
  "4.2": [2, { 0: "That's liberal or laissez-faire thinking (Adam Smith), not Marx.", 2: "Marx wanted to END class rule, not restore monarchy.", 3: "Marx accepted industry. He wanted workers to control it." }],
  "4.3": [3, { 0: "Japan ended isolation and deliberately modernized.", 2: "Japan was never colonized. It became an imperial power itself.", 3: "Japan ADOPTED Western technology selectively." }],
  "5.0": [1, { 0: "The Berlin Conference ORGANIZED colonization. The slave trade had ended earlier.", 2: "It divided Africa among Europeans rather than freeing it.", 3: "The League of Nations came after WWI (1920)." }],
  "5.1": [1, { 0: "Social Darwinism was used to SUPPORT imperialism.", 2: "Unions opposed that kind of thinking.", 3: "It was used to justify racial hierarchy, not to end slavery." }],
  "5.2": [2, { 0: "India didn't gain independence until 1947.", 2: "The rebellion ended what remained of the Mughal Empire.", 3: "Britain tightened its control of India." }],
  "5.3": [2, { 0: "Britain WON the Opium Wars.", 2: "The Qing fell in 1911, decades later.", 3: "China gained no colonies. It LOST sovereignty to foreign powers." }],
  "6.0": [0, { 0: "The Depression came AFTER WWI (1929).", 2: "The Cold War followed WWII.", 3: "Decolonization mostly happened after WWII." }],
  "6.1": [1, { 0: "Total war mobilized CIVILIANS and economies, not just soldiers.", 2: "WWI was fought on land, at sea and in the air.", 3: "Colonies sent troops and resources." }],
  "6.2": [3, { 1: "The Cold War ended in 1991, long after fascism rose.", 2: "Most of Africa was still colonized then.", 3: "The Green Revolution came in the 1960s." }],
  "6.3": [2, { 0: "Stalin led a COMMUNIST state and didn't restore a monarchy.", 2: "The plans were state-controlled, the opposite of a free market.", 3: "Decolonization wasn't a Soviet domestic plan." }],
  "7.0": [0, { 1: "European colonization of Asia happened centuries earlier. These were Cold War conflicts.", 2: "WWI was 1914–18, and these wars were in the 1950s–70s.", 3: "They were ideological (capitalism vs. communism), not religious." }],
  "7.1": [1, { 0: "India's movement is famous for NONviolence. Algeria's was the violent example.", 2: "The Soviet army didn't free India.", 3: "India led the Non-Aligned Movement and didn't join NATO." }],
  "7.2": [1, { 0: "Algeria's independence required a long, violent war.", 2: "The UN didn't grant it by vote.", 3: "It took far more than a boycott." }],
  "7.3": [1, { 0: "The Marshall Plan rebuilt Western Europe after 1947.", 2: "The Great Leap Forward was Chinese.", 3: "The Berlin Conference was 1884, about Africa." }],
  "8.0": [0, { 0: "It INCREASED food production.", 2: "Pollution wasn't solved. Fertilizer use even added environmental costs.", 3: "The Green Revolution came in the 1960s, not the start of the Cold War." }],
  "8.1": [1, { 0: "The Berlin Wall symbolized Cold War DIVISION.", 2: "The Sepoy Rebellion was an 1857 revolt against imperial rule.", 3: "Feudalism was medieval." }],
  "8.2": [2, { 1: "Mao led communist China.", 2: "Bismarck unified Germany in 1871.", 3: "Bolívar led Latin American independence in the 1800s." }],
  "8.3": [3, { 0: "Critics argue the opposite: benefits are uneven.", 2: "Trade grew enormously.", 3: "Multinationals EXPANDED with globalization." }],
};
