// "AP Trap" for every concept in content/biology.js: how the exam catches students on it.
// Key "unit.concept" -> trap
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["biology"] = {
  "0.0": "Hydrogen bonds form BETWEEN water molecules. The bonds INSIDE a water molecule are covalent. Questions about cohesion or specific heat are always about the between-molecule bonds.",
  "0.1": "Dehydration synthesis REMOVES water to build a polymer. Hydrolysis ADDS water to break it. Answer choices love to swap the two.",
  "0.2": "A single amino acid change alters primary structure first, and that can wreck the whole 3-D fold. \"Only one amino acid changed\" doesn't mean \"little effect.\"",
  "0.3": "RNA uses uracil (U), not thymine (T). Nitrogen shows up in proteins and nucleic acids, while phosphorus marks nucleic acids and phospholipids.",
  "1.0": "Prokaryotes have ribosomes but NO membrane-bound organelles. Questions often offer \"ribosomes\" as a trap for what prokaryotes lack.",
  "1.1": "Bigger cells have a SMALLER surface-area-to-volume ratio. Volume grows faster (s³) than surface area (s²).",
  "1.2": "Facilitated diffusion uses a protein but NO ATP. Using a protein doesn't make it active transport. Going against the gradient does.",
  "1.3": "Water moves toward HIGHER solute concentration, which means LOWER water potential. Hypertonic means more solute outside, so the cell loses water.",
  "2.0": "Enzymes lower activation energy. They don't change ΔG or get used up. More substrate beats a COMPETITIVE inhibitor but not a noncompetitive one.",
  "2.1": "The O₂ from photosynthesis comes from WATER, not CO₂. And the Calvin cycle isn't \"the dark reactions happening at night\": it needs ATP and NADPH from light.",
  "2.2": "The electron transport chain makes ATP indirectly. The H⁺ gradient powers ATP synthase. Anything that leaks H⁺ lowers ATP even if electrons keep flowing.",
  "2.3": "Fermentation's job is to regenerate NAD⁺ so glycolysis can continue. It makes NO extra ATP beyond glycolysis's 2.",
  "3.0": "Many ligands never enter the cell. They bind surface receptors. Blocking the receptor blocks the response even when plenty of ligand is present.",
  "3.1": "\"Negative\" feedback means it REVERSES a change (like a thermostat). It isn't \"bad.\" Childbirth contractions and fruit ripening are POSITIVE feedback.",
  "3.2": "DNA is copied in S phase, not during mitosis. Chromosomes arrive at metaphase already duplicated.",
  "3.3": "Proto-oncogenes are the accelerator (a gain-of-function mutation causes cancer). Tumor suppressors like p53 are the brakes (loss of function causes cancer).",
  "4.0": "Independent assortment (metaphase I) and crossing over (prophase I) are different sources of variation. Know which phase each happens in.",
  "4.1": "For \"A AND B\", MULTIPLY probabilities. Heterozygous (Aa) is 1/2 of an Aa × Aa cross, not 1/4.",
  "4.2": "Sons get their X from their MOTHER. An X-linked trait in a son traces back to mom, never dad.",
  "4.3": "Chi-square never \"proves\" a hypothesis. If χ² < the critical value, you FAIL TO REJECT the null.",
  "5.0": "DNA polymerase only builds 5′→3′. That single fact is why there's a lagging strand with Okazaki fragments.",
  "5.1": "Introns are REMOVED and exons are EXpressed. Alternative splicing lets one gene make several proteins.",
  "5.2": "Pair codons with anticodons, and remember that mRNA is read 5′→3′. Many trap answers are written backward or with T instead of U.",
  "5.3": "Every cell has the SAME DNA. Cells differ because of which genes are EXPRESSED. Lac operon: lactose present means the repressor is OFF and the genes are ON.",
  "6.0": "Individuals don't evolve; populations do. And traits don't appear because they're \"needed\": variation exists first, then selection acts on it.",
  "6.1": "Carriers (heterozygotes) are 2pq, not p² or q². Find q from q² first (the recessive phenotype frequency).",
  "6.2": "Bottleneck = a disaster shrinks an existing population. Founder = a few individuals START a new one. Both are random, not adaptive.",
  "6.3": "Homologous structures (same bones, different jobs) show common ancestry. Analogous structures (same job, different origin) show convergent evolution.",
  "7.0": "Energy FLOWS and is lost as heat (about 10% passes up each level). Matter CYCLES. Food-web arrows point toward the eater.",
  "7.1": "Logistic growth is fastest at K/2, not at K. At K, growth is zero.",
  "7.2": "A keystone species is defined by its OUTSIZED effect, not by being the most common species.",
  "7.3": "Invasive species thrive because they lack natural predators, competitors or diseases in the new habitat. Explain that mechanism, not just \"they spread.\"",
};
