// "AP Trap" for every concept in content/calculus-ab.js (Calculus BC Units 1–8 reuse these).
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["calculus-ab"] = {
  "0.0": "A limit can exist even where f(a) is undefined (a hole). \"f(3) doesn't exist\" doesn't mean \"the limit doesn't exist.\"",
  "0.1": "0/0 is NOT an answer. It's a signal to factor, rationalize or use a known limit before substituting again.",
  "0.2": "To justify continuity, show all three: f(a) is defined, the limit exists, and they're EQUAL. Graders want all three stated.",
  "0.3": "The IVT only applies to CONTINUOUS functions on a CLOSED interval. State the conditions or lose the point.",
  "1.0": "lim(h→0) [f(a+h) − f(a)]/h is a derivative in disguise. Recognize it instead of expanding.",
  "1.1": "Differentiable implies continuous, but NOT the other way around: |x| is continuous with a corner at 0.",
  "1.2": "(fg)′ ≠ f′g′. The product rule has TWO terms, and the quotient rule's order matters: (f′g − fg′)/g².",
  "1.3": "Tangent line: y − f(a) = f′(a)(x − a). Use f′(a) for the slope and f(a) for the point. Mixing them up is the most common slip.",
  "2.0": "Chain rule: always multiply by the derivative of the INSIDE. d/dx e^(x²) needs the 2x.",
  "2.1": "When differentiating implicitly, every y term gets a dy/dx, and products like xy need the PRODUCT rule.",
  "2.2": "(f⁻¹)′(b) = 1/f′(a), where f(a) = b. Evaluate f′ at the ORIGINAL x-value, not at b.",
  "2.3": "For an implicit second derivative, substitute your dy/dx back in. Don't leave y′ inside the answer.",
  "3.0": "Speeding up = v and a have the SAME sign. Velocity alone can't tell you.",
  "3.1": "In related rates, DIFFERENTIATE FIRST, then plug in numbers. Plugging in early turns variables into constants.",
  "3.2": "Concave up → the tangent line UNDERestimates. Concave down → it OVERestimates. Free-response questions often ask which, with a reason.",
  "3.3": "L'Hôpital needs 0/0 or ∞/∞ first, and you must SHOW that. It's f′/g′ taken separately, not the quotient rule.",
  "4.0": "The MVT needs continuity on [a, b] AND differentiability on (a, b). State both to earn the point.",
  "4.1": "f′ = 0 doesn't guarantee an extremum (x³ at 0). Justify with a SIGN CHANGE of f′.",
  "4.2": "An inflection point needs f″ to CHANGE SIGN, not just equal 0.",
  "4.3": "For absolute extrema, check critical points AND ENDPOINTS (the Candidates Test).",
  "5.0": "Increasing f → right sum OVERestimates and left sum UNDERestimates. Concave up → trapezoid OVERestimates.",
  "5.1": "The integral of a RATE is the total CHANGE. The amount at time b = starting amount + ∫ rate. Don't forget the starting amount.",
  "5.2": "d/dx ∫(a to g(x)) f(t) dt = f(g(x))·g′(x). Forgetting the g′(x) chain factor is the classic mistake.",
  "5.3": "With definite u-substitution, change the bounds to u-values (or switch back to x before evaluating). And +C on indefinite integrals.",
  "6.0": "Slopes that depend only on y are the same across each ROW. Slopes that depend only on x are the same down each COLUMN.",
  "6.1": "Add +C right after integrating, BEFORE solving for y. Then use the initial condition. Missing C costs most of the points.",
  "6.2": "dy/dt = ky gives y = y₀e^(kt). A doubling time T means k = ln 2 / T, not 2/T.",
  "7.0": "Average VALUE = (1/(b − a))∫f dx. That isn't the average RATE of change, [f(b) − f(a)]/(b − a).",
  "7.1": "Total distance = ∫|v| dt. Displacement = ∫v dt. The exam loves a v that changes sign.",
  "7.2": "Area = ∫(top − bottom). Find the intersection points for the bounds, and check which curve is on top.",
  "7.3": "Washer: π∫(R² − r²), NOT π∫(R − r)². Cross sections don't use π.",
};
