// "AP Trap" for every concept in content/chemistry.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["chemistry"] = {
  "0.0": "Moles = mass ÷ molar mass. Average atomic mass is weighted by ABUNDANCE, not a simple average of the isotopes.",
  "0.1": "For empirical formulas, convert percentages to MOLES before finding the ratio. Mass ratios aren't mole ratios.",
  "0.2": "Electrons leave 4s BEFORE 3d when forming ions. In PES, the peak farthest left (highest binding energy) is 1s.",
  "0.3": "Explain trends with Coulombic attraction (protons, distance, shielding). \"Wants a full octet\" earns no credit.",
  "1.0": "Metallic bonding (a sea of electrons) explains conductivity. Interstitial alloys have SMALL atoms in the gaps; substitutional alloys have similar-sized atoms.",
  "1.1": "The best Lewis structure has formal charges closest to ZERO. Resonance structures are an AVERAGE, not a flip back and forth.",
  "1.2": "Molecular shape ignores lone pairs even though they affect the angles. NH₃ is trigonal PYRAMIDAL, not tetrahedral.",
  "1.3": "Polar bonds don't make a molecule polar if the shape is symmetrical (CO₂, CH₄).",
  "2.0": "Boiling overcomes INTERmolecular forces, not covalent bonds. Hydrogen bonding needs H bonded to N, O or F.",
  "2.1": "Covalent network solids (diamond, SiO₂) have very high melting points. Don't lump them in with molecular solids.",
  "2.2": "Use KELVIN in PV = nRT. Real gases deviate most at HIGH pressure and LOW temperature.",
  "2.3": "Molarity uses LITERS of SOLUTION. In Beer's law, absorbance is proportional to concentration.",
  "3.0": "Dissolving an ionic solid is a gray area on the exam. Justify your answer either way, with particle-level reasoning.",
  "3.1": "In net ionic equations, only STRONG electrolytes in solution are split into ions. Keep solids, liquids, gases and weak acids together.",
  "3.2": "The limiting reactant is the one that makes the LEAST product, not necessarily the one with fewer grams or moles.",
  "3.3": "At the equivalence point, mol acid = mol base (by ratio), which isn't always pH 7. OIL RIG: Oxidation Is Loss of electrons.",
  "4.0": "Reaction orders come from EXPERIMENTAL data, not from the balanced equation's coefficients (except for elementary steps).",
  "4.1": "A straight-line plot identifies the order: [A] (zero), ln[A] (first), 1/[A] (second). First-order half-life is constant.",
  "4.2": "A catalyst lowers Ea but does NOT change ΔH or K. It speeds up both directions equally.",
  "4.3": "The slow step sets the rate law. Intermediates are made then used up. Catalysts are used up then remade.",
  "5.0": "If the water gets HOTTER, the reaction RELEASED heat (ΔH_rxn < 0). Signs flip between the system and its surroundings.",
  "5.1": "q = mcΔT gives heat for the WATER. q_rxn = −q_water. Divide by moles for ΔH in kJ/mol.",
  "5.2": "Bond enthalpy: ΔH = bonds BROKEN − bonds FORMED. Reverse a reaction → flip the sign. Multiply it → multiply ΔH.",
  "5.3": "During a phase change the temperature stays CONSTANT. The energy goes into overcoming attractions, not raising temperature.",
  "6.0": "Leave pure solids and liquids OUT of K. K changes only with TEMPERATURE.",
  "6.1": "Q < K → shifts toward PRODUCTS. Q > K → shifts toward reactants. Compare them before predicting.",
  "6.2": "Adding reactant shifts equilibrium but does NOT change K. Only temperature changes K.",
  "6.3": "A common ion LOWERS solubility. Ksp expressions multiply ion concentrations raised to their coefficients.",
  "7.0": "pH is logarithmic: 1 pH unit = 10× the [H⁺]. pH + pOH = 14 only at 25 °C.",
  "7.1": "Weak acids only partly ionize: use Ka and [H⁺] ≈ √(Ka·C). Don't treat them as strong.",
  "7.2": "A buffer needs a WEAK acid plus its CONJUGATE BASE. A strong acid with its salt isn't a buffer.",
  "7.3": "At HALF-equivalence, pH = pKa. For a weak acid titrated with a strong base, the equivalence pH is ABOVE 7.",
  "8.0": "Making gas from solids or liquids means ΔS > 0. More moles of gas means more entropy.",
  "8.1": "\"Thermodynamically favored\" (ΔG < 0) says nothing about SPEED. A favored reaction can be very slow.",
  "8.2": "Don't multiply E° by coefficients. Cell potential is intensive. AN OX / RED CAT: oxidation at the anode.",
  "8.3": "In electrolysis, moles of e⁻ = It/F, then use the mole ratio. Units of time must be SECONDS.",
};
