// "AP Trap" for every concept in content/physics-2.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["physics-2"] = {
  "0.0": "Temperature must be in KELVIN. Average KE ∝ T means doubling from 20 °C to 40 °C does NOT double the energy.",
  "0.1": "AP defines W as work done ON the gas: ΔU = Q + W. Compression makes W positive. Using the other convention flips your signs.",
  "0.2": "Work is the AREA under a PV curve, not the slope. For a cycle, the net work is the ENCLOSED area.",
  "0.3": "Heat flows from hot to cold on its own, and the entropy of an isolated system never decreases. Don't confuse \"heat\" with \"temperature.\"",
  "1.0": "Coulomb's law is inverse SQUARE. Scaling questions combine the charge factors AND 1/r² factors.",
  "1.1": "Negative charges feel forces OPPOSITE to E. Field direction is defined for a positive test charge.",
  "1.2": "Potential is a SCALAR: add values with signs, not as vectors. Moving along an equipotential does zero work.",
  "1.3": "Inside a conductor in equilibrium E = 0, and charge sits on the outer surface. Induction polarizes without transferring charge.",
  "2.0": "Current isn't used up by resistors. The same current flows through every element in series.",
  "2.1": "Adding a resistor in PARALLEL lowers total resistance and INCREASES total current. This is counterintuitive and heavily tested.",
  "2.2": "Kirchhoff's loop rule is energy conservation. The junction rule is charge conservation. Justifications should name which principle.",
  "2.3": "At steady state a charged capacitor carries NO current: treat its branch as open.",
  "3.0": "Magnetic force is perpendicular to velocity, so it does NO work and can't change speed. A charge moving parallel to B feels no force.",
  "3.1": "Use the right-hand rule for POSITIVE charges and flip it for negative ones. Many wrong answers are simply reversed.",
  "3.2": "Field lines around a straight wire are CIRCLES, not radial lines. B ∝ 1/r, not 1/r².",
  "3.3": "Only a CHANGING flux induces emf. A magnet at rest inside a coil induces nothing.",
  "4.0": "Measure angles from the NORMAL, not the surface.",
  "4.1": "Frequency stays the same when light changes media. Speed and wavelength change. Bending TOWARD the normal means entering a higher n.",
  "4.2": "Total internal reflection requires going from HIGHER n to LOWER n, beyond the critical angle.",
  "4.3": "An object inside the focal length of a converging lens gives a VIRTUAL, upright, magnified image (a negative dᵢ).",
  "5.0": "The medium sets wave speed. Changing frequency changes wavelength, not speed.",
  "5.1": "In the Doppler effect, the SOURCE's actual frequency doesn't change. Only the observed frequency does.",
  "5.2": "For a string fixed at both ends, the fundamental λ = 2L. Harmonics are whole-number multiples of f₁.",
  "5.3": "A larger λ or a SMALLER slit spacing d spreads fringes farther apart.",
  "6.0": "Intensity controls HOW MANY electrons are ejected. Frequency controls their ENERGY. Below threshold, no electrons at any intensity.",
  "6.1": "Photon energy equals the DIFFERENCE between energy levels, not the energy of either level.",
  "6.2": "A larger momentum means a SHORTER de Broglie wavelength. Everyday objects have wavelengths far too small to notice.",
  "6.3": "Balance BOTH mass number and atomic number in decay equations. An alpha particle is ⁴₂He.",
};
