// "AP Trap" for every concept in content/physics-1.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["physics-1"] = {
  "0.0": "Zero velocity doesn't mean zero acceleration. At the top of a throw, v = 0 but a = g downward.",
  "0.1": "SLOPE of x–t = velocity. SLOPE of v–t = acceleration. AREA under v–t = displacement. Graph questions test whether you use slope or area.",
  "0.2": "The kinematic equations only work with CONSTANT acceleration. Check that before you use them.",
  "0.3": "Horizontal speed doesn't change fall time. Horizontal and vertical motion are independent, linked only by time.",
  "1.0": "Moving at constant velocity needs NO net force. There's no \"force of motion.\" Third-law pairs act on DIFFERENT objects, so they never cancel.",
  "1.1": "The normal force isn't always mg. It changes on ramps, in accelerating elevators, and when other vertical forces act.",
  "1.2": "Static friction is only as large as NEEDED (up to μₛN). Kinetic friction is μₖN. Don't use μN for an object that isn't sliding.",
  "1.3": "\"Centripetal force\" isn't a new force on your diagram. It's whatever real force (tension, friction, gravity) points toward the center.",
  "2.0": "A force perpendicular to the motion (like the normal force on flat ground) does ZERO work. Holding something still does zero work.",
  "2.1": "KE ∝ v². Double the speed and KE QUADRUPLES. Use VERTICAL height for mgh, not path length.",
  "2.2": "Mechanical energy is conserved only if no friction or outside work acts on the system. DEFINE the system first. Friction turns energy into heat.",
  "2.3": "Power = energy per TIME. Lifting at constant speed: P = mgh/t, or P = Fv.",
  "3.0": "Airbags don't reduce the change in momentum. They increase the TIME, which reduces the FORCE (FΔt = Δp).",
  "3.1": "Momentum is conserved only when the NET EXTERNAL force is zero. Momentum is a vector, so leftward motion needs a negative sign.",
  "3.2": "Momentum is conserved in EVERY collision (for an isolated system), but KE only in ELASTIC ones. Sticking together = perfectly inelastic.",
  "3.3": "With no external force, the center of mass moves at constant velocity, even while the parts collide or explode.",
  "4.0": "v = rω: points farther out move faster, but every point on a rigid body has the SAME ω.",
  "4.1": "Torque uses the LEVER ARM (the perpendicular distance). A force pointed straight at the pivot gives zero torque.",
  "4.2": "Rotational inertia depends on WHERE the mass is, not just how much: a hoop has a larger I than a disk of equal mass.",
  "4.3": "Static equilibrium needs ΣF = 0 AND Στ = 0. Pick a pivot at an unknown force to remove it from the torque equation.",
  "5.0": "Rolling objects split KE between translation and rotation. A smaller I (relative to mR²) means a FASTER roll downhill.",
  "5.1": "Pulling your arms in conserves L, but KE INCREASES (your muscles do work). Angular momentum conserved doesn't mean energy conserved.",
  "5.2": "Planets move FASTEST when CLOSEST to the Sun. Angular momentum is conserved because gravity exerts no torque about the Sun.",
  "6.0": "The restoring force points toward equilibrium and is proportional to displacement. That proportionality is what makes it SHM.",
  "6.1": "Period does NOT depend on amplitude. A pendulum's period doesn't depend on mass either (only L and g).",
  "6.2": "Speed is maximum at EQUILIBRIUM and zero at the extremes. Acceleration is maximum at the extremes.",
  "7.0": "Pressure depends on DEPTH, not container shape. Gauge pressure = ρgh; absolute pressure adds P₀.",
  "7.1": "Buoyant force uses the FLUID's density and the SUBMERGED volume. A floating object has F_b = weight.",
  "7.2": "Narrower pipe → FASTER flow (A₁v₁ = A₂v₂) → LOWER pressure (Bernoulli). The pressure drop surprises students.",
};
