// "AP Trap" for every concept in content/us-history.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["us-history"] = {
  "0.0": "Native American societies were NOT one culture. Tie each group's way of life to its environment (maize in the Southwest, mobile hunting on the Plains).",
  "0.1": "The Columbian Exchange went BOTH ways. Disease devastated the Americas, and American crops and silver transformed Europe.",
  "0.2": "The encomienda was about forced LABOR, not religion. The Valladolid Debate was about whether Native peoples deserved rights.",
  "1.0": "Don't treat \"the colonies\" as one place. Chesapeake = tobacco and servants → slavery. New England = towns, trade and Puritans. Middle = diverse and grain.",
  "1.1": "Slavery didn't dominate Virginia from the start. It grew over time, especially after Bacon's Rebellion (1676).",
  "1.2": "Salutary neglect = lax ENFORCEMENT of trade laws, which built habits of self-government. It didn't mean Britain ignored the colonies entirely.",
  "1.3": "The French relied on trade and alliances with Native peoples far more than the English did, so compare them by their relationships, not just their land claims.",
  "2.0": "Colonists objected to taxation WITHOUT REPRESENTATION, not to taxes in general. That's the causation the exam wants.",
  "2.1": "Revolutionary ideals raised questions about slavery and women's rights but didn't resolve them. Expect \"to what extent\" framing.",
  "2.2": "Shays' Rebellion exposed the Articles' weakness, which led to the Constitution. The Great Compromise was about REPRESENTATION, not slavery.",
  "2.3": "The Federalist PARTY (Hamilton) isn't identical to the \"Federalists\" who supported ratification. Watch the dates.",
  "3.0": "Jacksonian democracy expanded voting for WHITE MEN. Always note who was excluded.",
  "3.1": "The cotton gin INCREASED slavery by making cotton more profitable. It didn't reduce the need for labor.",
  "3.2": "Reform movements (abolition, temperance, women's rights) grew OUT OF the Second Great Awakening's belief in human perfectibility, so make that causal link.",
  "3.3": "Worcester v. Georgia sided with the Cherokee, but removal happened anyway. Don't confuse the ruling with the outcome.",
  "4.0": "The Kansas-Nebraska Act effectively REPEALED the Missouri Compromise line by allowing popular sovereignty north of 36°30′.",
  "4.1": "Dred Scott said Congress could NOT ban slavery in the territories, which destroyed the basis of earlier compromises.",
  "4.2": "The Emancipation Proclamation freed people only in areas IN REBELLION. The 13th Amendment ended slavery everywhere.",
  "4.3": "13-14-15 = free, citizen, vote (for men only). Reconstruction ended with the Compromise of 1877, not an amendment.",
  "5.0": "Vertical integration (Carnegie) = control every STAGE of production. Horizontal integration (Rockefeller) = buy out COMPETITORS.",
  "5.1": "Government usually sided with BUSINESS in Gilded Age strikes (troops at Pullman, court injunctions).",
  "5.2": "\"New\" immigrants came from Southern and Eastern Europe. Nativism targeted them and led to Chinese exclusion (1882).",
  "5.3": "The Dawes Act broke up tribal land to force assimilation, and Native nations LOST land. Populists wanted free SILVER, not gold.",
  "6.0": "The U.S. entered WWI over submarine warfare and the Zimmermann Telegram. The Senate REJECTED the League of Nations.",
  "6.1": "Progressive amendments in order: 16 income tax, 17 direct election of senators, 18 Prohibition, 19 women's suffrage.",
  "6.2": "The 1920s were a clash of modern culture (jazz, the Harlem Renaissance) and backlash (quotas, the KKK, the Red Scare). Argue both sides.",
  "6.3": "The New Deal didn't fully end the Depression; WWII spending did most of that. Social Security is REFORM (permanent), not just relief.",
  "7.0": "Containment has many forms: the Truman Doctrine (military and economic aid), the Marshall Plan (economic recovery), NATO (alliance). Match the tool to the goal.",
  "7.1": "Brown v. Board OVERTURNED Plessy. The civil rights movement used many strategies across decades, not one event.",
  "7.2": "Suburbanization was pushed by the GI Bill and highways, and redlining shut many Black families out. Include that limit.",
  "7.3": "The 1960s–70s brought BOTH liberal movements and a conservative backlash (the New Right). Continuity-and-change essays need both.",
  "8.0": "Reagan CUT top tax rates and deregulated while RAISING defense spending. Don't write \"cut spending\" across the board.",
  "8.1": "Post-9/11 debates are about SECURITY vs. CIVIL LIBERTIES (the Patriot Act), which makes a classic continuity-over-time theme.",
  "8.2": "After 1980 the economy shifted from manufacturing to SERVICE and INFORMATION jobs. Manufacturing jobs declined.",
};
