// "AP Trap" for every concept in content/world-history.js.
window.AP_TRAPS = window.AP_TRAPS || {};
window.AP_TRAPS["world-history"] = {
  "0.0": "Song innovations (champa rice, paper money, the Grand Canal) matter for their EFFECTS: population growth and commercialization. Name the effect, not just the invention.",
  "0.1": "By 1200 the Abbasid Caliphate was fragmented. Dar al-Islam is a cultural and religious sphere, not one empire.",
  "0.2": "Religions changed as they spread (syncretism), for example Buddhism blending with local beliefs. \"Religion X spread\" alone earns less than HOW it adapted.",
  "0.3": "Compare state-building by LABOR and TRIBUTE: the Mexica took tribute, while the Inca took mit'a labor. Comparison questions want the similarity AND the difference.",
  "1.0": "The Silk Roads mostly carried LUXURY goods because of high transport costs. Bulk goods traveled by sea.",
  "1.1": "Mongol rule is double-edged: it boosted trade and the transfer of technology, AND it spread the Black Death.",
  "1.2": "Indian Ocean trade grew because of monsoon knowledge and borrowed technology (the lateen sail, astrolabe). Link the technology to the growth.",
  "1.3": "Mansa Musa's hajj is evidence of Mali's WEALTH and its ties to the Islamic world. It didn't begin trans-Saharan trade.",
  "2.0": "\"Gunpowder empires\" expanded with firearms, but also held power through administration. Don't reduce the answer to guns alone.",
  "2.1": "The devshirme recruited people. Tax farming raised revenue. These are different tools, and prompts often ask to tell them apart.",
  "2.2": "Legitimacy (why people accept a ruler) isn't the same as control (how rulers enforce power). Monuments and religion are LEGITIMACY.",
  "2.3": "The Ottoman–Safavid rivalry was Sunni versus Shia. The Reformation split CHRISTIANITY. Don't mix the two conflicts.",
  "3.0": "Much European maritime technology was ADAPTED from Asia and the Islamic world (the compass, astrolabe, lateen sail).",
  "3.1": "The Columbian Exchange affected each side differently: death from disease in the Americas, population GROWTH from new crops in Afro-Eurasia.",
  "3.2": "Joint-stock companies spread RISK among shareholders. They were private ventures backed by the state, not government departments.",
  "3.3": "Colonial labor systems differed: encomienda and hacienda (coerced Native labor) versus chattel slavery (hereditary). Name the right one for the region.",
  "4.0": "The Haitian Revolution is the ONLY successful revolt of enslaved people to found a state. It's a favorite comparison with the American and French Revolutions.",
  "4.1": "Nationalism can UNIFY (Germany, Italy) or BREAK APART multiethnic empires (the Ottomans, Austria-Hungary). Know both directions.",
  "4.2": "Explain WHY Britain industrialized first: coal, iron, capital, labor and colonies. \"Because of the steam engine\" isn't a cause.",
  "4.3": "Responses to industrialization ranged from reform (unions, laws) to revolution (Marxism) to state-led modernization (Meiji Japan). Match the response to the society.",
  "5.0": "Imperial motives were ECONOMIC (raw materials, markets) and IDEOLOGICAL (Social Darwinism). Strong answers name both.",
  "5.1": "After 1857, India went from Company rule to CROWN rule (the Raj). The Mughal Empire ended then.",
  "5.2": "Resistance took many forms: armed revolt, religious movements (the Ghost Dance) and new states (Ethiopia at Adwa). Some of it succeeded.",
  "5.3": "Economic imperialism can mean control WITHOUT formal colonies, as with the Opium Wars and spheres of influence in China.",
  "6.0": "Old empires fell from INTERNAL weakness plus external pressure (the Qing, the Ottomans, Russia). Give both causes.",
  "6.1": "WWI was global because of empires: colonial soldiers and resources were essential. Don't treat it as only European.",
  "6.2": "The Great Depression helped CAUSE the rise of fascism by discrediting democracies. Link the economic crisis to the political result.",
  "6.3": "Genocide questions expect specific examples (the Holocaust, the Armenian genocide, Cambodia, Rwanda) and their causes, such as ideology and ethnic nationalism.",
  "7.0": "The Cold War was mostly fought through PROXY wars and competition, not direct U.S.–Soviet combat.",
  "7.1": "Decolonization varied: negotiated (Ghana), nonviolent mass movements (India), violent wars (Algeria, Kenya). Comparison is the key skill.",
  "7.2": "Mao's Great Leap Forward caused a FAMINE. State-directed development could fail disastrously.",
  "7.3": "The USSR collapsed from economic stagnation, overspending and reform (glasnost/perestroika). It wasn't military defeat by the U.S.",
  "8.0": "Technology's benefits were UNEVEN. The Green Revolution raised yields but had environmental and social costs.",
  "8.1": "Economic globalization has winners and losers. Balanced answers mention both growth and inequality.",
  "8.2": "Rights movements after 1900 spread across borders and inspired one another (civil rights and anti-apartheid). Show those connections.",
  "8.3": "Global culture spreads through blending AND backlash (movements reasserting religion or nationalism).",
};
